name: Sync spiders to Airtable
 
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'city_scrapers/spiders/**.py'
 
jobs:
  sync:
    uses: City-Bureau/city-scrapers-core/.github/workflows/sync-airtable.yml@main
    secrets:
      AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE: ${{ secrets.SLUGS_TABLE_ID }}
      AIRTABLE_BACKLOG_TABLE: ${{ secrets.BACKLOG_TABLE_ID }}
 