name: Sync spiders to Airtable
 
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'city_scrapers/spiders/**.py'
 
jobs:
  sync:
    uses: City-Bureau/city-scrapers-core/.github/workflows/sync-airtable.yml@main
    secrets:
      CS_AIRTABLE_PAT: ${{ secrets.CS_AIRTABLE_PAT }}
      CS_AIRTABLE_BASE_ID: ${{ secrets.CS_AIRTABLE_BASE_ID }}
      CS_SLUGS_TABLE_ID: ${{ secrets.CS_SLUGS_TABLE_ID }}
      CS_BACKLOG_TABLE_ID: ${{ secrets.CS_BACKLOG_TABLE_ID }}
 